apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: webapp-pod

  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30005
